### ISSUE TITLE
Question regarding the license

### ISSUE THREAD

**Issue by travisbrady** [hpclab/quickrank#1]
First, quickrank looks great, nicely executed project from what I can see.
But I have a question about the license.

I'd never encountered the RPL-1.5 before and so was unfamiliar with its purpose. 
Am I reading correctly that anything using quickrank must be open sourced?

What if a user is just running quickrank from the command line ala the example in the README https://github.com/hpclab/quickrank/blob/master/README.md#training ? 
Would they need to open source the command they ran within bash?

Is the goal to wholly prohibit use within any business?

**Comment by claudio-lucchese** [comment]
Dear Travis,

thanks for your interest in QuickRank.

The RPL licence forces to opensource any software component built around QuickRank, or using it,
including scripts.

In addition, the RPL licence prohibits any commercial use of QuickRank.
Indeed we wanted to address mostly the academic community.

Please let us know the use you want to do of QuickRank by contacting us at quickrank@isti.cnr.it

Best,
the QuickRank Team
http://quickrank.isti.cnr.it
