### ISSUE TITLE
Number of iterations for RankBoost

### ISSUE THREAD

**Issue by guidozuc** [hpclab/quickrank#10]
Hi, thanks for the great work in putting together QuickRank. 

A question regarding the parameters that control your implementation of RankBoost. This algorithm relies on a parameter that is the number of iterations. From QuickRank documentation, the parameter `max_iterations` seems related only to Coordinate Ascent and Line Search. Is it possible to set the number of iterations for RankBoost? And which flag should be used for this?

Thanks
Guido

**Comment by claudio-lucchese** [comment]
Dear Guido,

thanks for your interest in QuickRank.

The parameter you are looking for is `num-trees`. This is used to set the number of weak rankers used in RankBoost.

Best,
claudio

**Comment by guidozuc** [comment]
Thanks for the clarification Claudio!
