### ISSUE TITLE
can't find paramsmap..

### ISSUE THREAD

**Issue by dygwyp** [hpclab/quickrank#14]
Hello, I can't find the library: lib/paramsmap, could you provide it to me?

**Comment by strani** [comment]
The git server hosting this library is currently down, we are working on it.
In the meantime, I sent you an email (taken from your github profile) with a copy of this library, so that you can use it right away.
Best,
Salvatore

**Comment by strani** [comment]
Hi,
I saw your Issue opened on GitHub related to the paramsmap library missing
in the quickrank project.
The git server hosting this library is currently down, we are working on it.
In the meantime, I attached to the current email a copy of this library, so
that you can use it right away.
Best,
Salvatore Trani

Salvatore Trani, Ph.D.
High Performance Computing (HPC) Laboratory
Istituto di Scienza e Tecnologie dell'Informazione (ISTI)
National Research Council (CNR)
Area della Ricerca CNR di Pisa
Via G. Moruzzi 1, 56124 Pisa ITALY

phone: +39 050 621 3015
fax:   +39 050 315 2040
email: ***@***.***


Il giorno mar 14 dic 2021 alle ore 07:32 bruce_li ***@***.***>
ha scritto:

**Comment by rishabhdhenkawat** [comment]
can you please help me again with this issues

**Comment by strani** [comment]
What problem are you facing?

Il giorno lun 9 mag 2022 alle ore 22:22 rishabhdhenkawat <
***@***.***> ha scritto:
