### ISSUE TITLE
When generating condop-optimized code, the resulting ranker.cc won't compile

### ISSUE THREAD

**Issue by tjt7a** [hpclab/quickrank#3]
I trained a quickrank model using MSLR Fold1 data and then generated a CONDOP-optimized ranker.cc file.

It fails to compile, with the following error:
.../src/quickrank/src/scoring/ranker.cc:705:201: error: unable to find numeric literal operator ‘operator""f’
 ( v[71] <= 63.6842117f ? ( v[71] <= 63.4252243f ? ( v[91] <= 265.827332f ? ( v[21] <= 10f ? ( v[4

The issue is that some of the threshold values do not contain any decimal places, and the compiler isn't happy with a decimal-less float.

**Comment by francomarianardini** [comment]
Dear Tom,

thanks for your interest in QuickRank. We just committed a fix that solves the bug you discovered. Thanks a lot.

Best,

The QuickRank team
