### ISSUE TITLE
'make quickscore' fails with vpred ranker

### ISSUE THREAD

**Issue by tjt7a** [hpclab/quickrank#5]
When I attempt to compile the VPRED ranker, I get the following error:

[  3%] Built target pugixml
[ 94%] Built target quickrank_common
[ 96%] Building CXX object CMakeFiles/quickscore.dir/src/scoring/ranker.cc.o
.../quickrank/src/scoring/ranker.cc:1:1: error: expected unqualified-id before numeric constant
 703
 ^
make[3]: *** [CMakeFiles/quickscore.dir/src/scoring/ranker.cc.o] Error 1
make[2]: *** [CMakeFiles/quickscore.dir/all] Error 2
make[1]: *** [CMakeFiles/quickscore.dir/rule] Error 2
make: *** [quickscore] Error 2

My VPRED ranker starts like this:
703
7
root 0 133 0
node 1 0 107 1 11.8834181

**Comment by francomarianardini** [comment]
Hello Tom,

the VPRED plugin you are using is a converter from the QuickRank XML model format to the VPRED model format. The plugin outputs a textual file. The file should then be used with the original VPRED code by Nima Asadi et al., Runtime Optimizations for Tree-Based Machine Learning Models. IEEE Trans. Knowl. Data Eng. 26(9): 2281-2292 (2014).

Original VPRED code by Jimmy Lin: https://github.com/lintool/OptTrees
