### ISSUE TITLE
'make quickscore' fails with oblivious ranker

### ISSUE THREAD

**Issue by tjt7a** [hpclab/quickrank#6]
When I attempt to compile the OBLIVIOUS ranker, I get the following error:

[  3%] Built target pugixml
[ 94%] Built target quickrank_common
[ 96%] Building CXX object CMakeFiles/quickscore.dir/src/scoring/ranker.cc.o
...
.../src/quickrank/src/scoring/ranker.cc:2123:1: error: too many initializers for ‘const float [0]’
.../tjt7a/src/quickrank/src/scoring/ranker.cc:2123:1: error: too many initializers for ‘const float [0]’
make[3]: *** [CMakeFiles/quickscore.dir/src/scoring/ranker.cc.o] Error 1
make[2]: *** [CMakeFiles/quickscore.dir/all] Error 2
make[1]: *** [CMakeFiles/quickscore.dir/rule] Error 2
make: *** [quickscore] Error 2

**Comment by tjt7a** [comment]
From the top of the file, this seems incorrect:

#define N 703 // no. of trees
#define M 0 // max tree depth
#define F 1 // max number of leaves

**Comment by claudio-lucchese** [comment]
Apparently you tried to build an oblivious scorer from a model that was not oblivious.
Can you please help us to regenerate the error?

The correct flow of execution should be the following:

1. Train an oblivious model
`./bin/quicklearn --algo OBVMART --num-trees 10 --train quickranktestdata/msn1/msn1.fold1.train.5k.txt --model-out model.xml`

1. Transform the model into c code
`./bin/quicklearn --model-file model.xml --code-file model.cc --generator oblivious`

1. replace the dummy ranker.cc and compile the scorer
`cp model.cc src/scoring/ranker.cc`
`make -C build_dir quickscore`

1. run the scorer
`./bin/quickscore -d quickranktestdata/msn1/msn1.fold1.test.5k.txt -s qs.scores`
